name: "Merge Dev to Main"
description: "Merges dev branch with main branch"

inputs:
  github_token:
    description: "Token for Github API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Merge dev into main
      uses: devmasx/merge-branch@v1.4.0
      with:
        type: now
        from_branch: dev
        target_branch: main
        github_token: ${{ inputs.github_token }}