name: "JUnit Tests"
description: "Runs JUnit tests"

inputs:
  s3_bucket:
    description: "S3 bucket name"
    required: true
  s3_region:
    description: "S3 region name"
    required: true
  s3_access_key:
    description: "Access Key for S3 authentication"
    required: true
  s3_secret_key:
    description: "Secret Key for S3 authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set Execution Permissions
      run: |
        chmod +x ./deploy/scripts/*.sh
        chmod +x ./gradlew
      shell: bash

    - name: Build Selenium environment
      run: sudo ./deploy/scripts/build_selenium_environment.sh
      shell: bash

    - name: Export Selenium environment variables
      run: |
        echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
        echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV
        echo "DRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV
      shell: bash

    - name: Export S3 environment variables
      run: |
        echo "S3_BUCKET=${{ inputs.s3_bucket }}" >> $GITHUB_ENV
        echo "S3_REGION=${{ inputs.s3_region }}" >> $GITHUB_ENV
        echo "S3_ACCESS_KEY=${{ inputs.se_access_key }}" >> $GITHUB_ENV
        echo "S3_SECRET_KEY=${{ inputs.s3_secret_key }}" >> $GITHUB_ENV
      shell: bash

    - name: Test
      run: printenv S3_BUCKET
      shell: bash

    - name: Run Gradle Build and Tests
      run: ./gradlew clean build test
      shell: bash