name: "Merge Dev to Main Workflow"

on:
  workflow_call:
    inputs:
      bot_token:
        description: "The API token used to send messages via Telegram bot"
        required: true
        type: string
      chat_id:
        description: "Unique identifier of the Telegram chat"
        required: true
        type: string
    github_token:
      description: "Token for Github API"
      required: true
      type: string

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - name: Notify start
        uses: ./.github/actions/send-notification/
        with:
          bot_token: ${{ inputs.bot_token }}
          chat_id: ${{ inputs.chat_id }}
          message: "⚙️ Starting Merge dev to main!"

  merge:
    needs: notify_start
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: ./.github/actions/merge_dev_to_main/
        with:
          github_token: ${{ inputs.github_token }}

  notify_end:
    needs: merge
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set result message
        run: |
          if [ "${{ needs.merge.result }}" == "success" ]; then
            echo "MESSAGE=⚙️ Merge dev to main completed successfully! ✅" >> $GITHUB_ENV
          else
            echo "MESSAGE=⚙️ Merge dev to main failed! ❌" >> $GITHUB_ENV
        shell: bash

      - name: Notify end
        uses: ./.github/actions/send-notification/
        with:
          bot_token: ${{ inputs.bot_token }}
          chat_id: ${{ inputs.chat_id }}
          message: "${{ env.MESSAGE }}"