name: "Postman Tests Workflow"

on:
  workflow_call:
    inputs:
      bot_token:
        description: "The API token used to send messages via Telegram bot"
        required: true
        type: string
      chat_id:
        description: "Unique identifier of the Telegram chat"
        required: true
        type: string
      postman_api_key:
        description: "Key for postman API"
        required: true
        type: string
      server_url:
        description: "Server's Url"
        required: true
        type: string
      schema_url:
        description: "Schema's Url"
        required: true
        type: string

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - name: Notify start
        uses: ./.github/actions/send_notification/
        with:
          bot_token: ${{ inputs.bot_token }}
          chat_id: ${{ inputs.chat_id }}
          message: "⚙️ Starting Postman tests!"

  run_tests:
    needs: notify_start
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/actions/postman_tests/
        with:
          postman_api_key: ${{ inputs.postman_api_key }}
          server_url: ${{ inputs.server_url }}
          schema_url: ${{ inputs.schema_url }}

  notify_end:
    needs: run_tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set result message
        run: |
          if [ "${{ needs.run_tests.result }}" == "success" ]; then
            echo "MESSAGE=⚙️ Postman tests completed successfully! ✅" >> $GITHUB_ENV
          else
            echo "MESSAGE=⚙️ Postman tests failed! ❌" >> $GITHUB_ENV
        shell: bash

      - name: Notify end
        uses: ./.github/actions/send_notification/
        with:
          bot_token: ${{ inputs.bot_token }}
          chat_id: ${{ inputs.chat_id }}
          message: "${{ env.MESSAGE }}"