name: "Wait for Deployment Workflow"

on:
  workflow_call:
    secrets:
      bot_token:
        description: "The API token used to send messages via Telegram bot"
        required: true
      chat_id:
        description: "Unique identifier of the Telegram chat"
        required: true
      railway_api_key:
        description: "Railway API key for authentication"
        required: true
      project_id:
        description: "Railway project ID"
        required: true
      service_id:
        description: "Railway service ID"
        required: true
      environment_id:
        description: "Railway environment ID"
        required: true

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Notify start
        uses: ./.github/actions/send_notification/
        with:
          bot_token: ${{ secrets.bot_token }}
          chat_id: ${{ secrets.chat_id }}
          message: "⚙️ Starting to wait for Deployment!"

  wait_deployment:
    needs: notify_start
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Wait deployment
        uses: ./.github/actions/wait_deployment/
        with:
          railway_api_key: ${{ secrets.railway_api_key }}
          project_id: ${{ secrets.project_id }}
          service_id: ${{ secrets.service_id }}
          environment_id: ${{ secrets.environment_id }}

  notify_end:
    needs: wait_deployment
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set result message
        run: |
          if [ "${{ needs.wait_deployment.result }}" == "success" ]; then
            echo "MESSAGE=⚙️ Railway Deployment completed successfully! ✅" >> $GITHUB_ENV
          else
            echo "MESSAGE=⚙️ Railway Deployment failed! ❌" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Notify end
        uses: ./.github/actions/send_notification/
        with:
          bot_token: ${{ secrets.bot_token }}
          chat_id: ${{ secrets.chat_id }}
          message: "${{ env.MESSAGE }}"